name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Change to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "MyDotNetApp"  # Replace with your Azure Web App name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: publish
